#if !canImport(ObjectiveC)
import XCTest

extension IntcodeComputerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IntcodeComputerTests = [
        ("testDay02Sample01", testDay02Sample01),
        ("testDay02Sample02", testDay02Sample02),
        ("testDay02Sample03", testDay02Sample03),
        ("testDay02Sample04", testDay02Sample04),
        ("testDay02Sample05", testDay02Sample05),
        ("testDay05Sample01", testDay05Sample01),
        ("testDay05Sample02", testDay05Sample02),
        ("testDay05Sample03", testDay05Sample03),
        ("testDay05Sample04", testDay05Sample04),
        ("testDay05Sample05", testDay05Sample05),
        ("testDay05Sample06", testDay05Sample06),
        ("testDay05Sample07", testDay05Sample07),
        ("testDay05Sample08", testDay05Sample08),
        ("testDay09Sample01", testDay09Sample01),
        ("testDay09Sample02", testDay09Sample02),
        ("testDay09Sample03", testDay09Sample03),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(IntcodeComputerTests.__allTests__IntcodeComputerTests),
    ]
}
#endif
